-- 코드를 입력하세요
SELECT R.REST_ID,REST_NAME, FOOD_TYPE,FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I
INNER JOIN REST_REVIEW R  ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE "서울%"
GROUP BY R.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC
