-- 코드를 입력하세요
SELECT HISTORY_ID,CAR_ID, DATE_FORMAT(start_date,"%Y-%m-%d") as START_DATE, DATE_FORMAT(END_DATE,"%Y-%m-%d") as END_DATE
, IF(DATEDIFF(END_DATE, START_DATE) >= 30, "장기 대여", "단기 대여") as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE year(start_date) = 2022 and month(start_date) = 9
ORDER BY HISTORY_ID DESC