SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
       DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
       
FROM USED_GOODS_BOARD AS UGB
INNER JOIN USED_GOODS_REPLY AS UGR
ON UGB.BOARD_ID = UGR.BOARD_ID

WHERE  MONTH(UGB.CREATED_DATE) = 10 AND YEAR(UGB.CREATED_DATE) = 2022
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC