-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, "%H") as HOUR, COUNT(DATE_FORMAT(DATETIME, "%H")) as COUNT
FROM ANIMAL_OUTS 
WHERE DATE_FORMAT(DATETIME, "%H") >=9 and DATE_FORMAT(DATETIME, "%H") < 20
GROUP BY DATE_FORMAT(DATETIME, "%H")
ORDER BY HOUR ASC