SELECT a.ID, a.GENOTYPE, b.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA a INNER JOIN ECOLI_DATA b
    ON a.PARENT_ID = b.ID and a.PARENT_ID is not null
WHERE LPAD(BIN(a.GENOTYPE & b.GENOTYPE),16,0) LIKE REPLACE(LPAD(BIN(b.GENOTYPE),16,0),0,'_')
ORDER BY a.ID