SELECT  A.title, A.board_id , B.reply_id, B.writer_id, B.contents, 
        DATE_FORMAT(B.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
        
FROM    USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY B
        ON A.BOARD_ID = B.BOARD_ID
WHERE   YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10
ORDER BY B.CREATED_DATE,A.TITLE

