-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(A.SALES) as TOTAL_SALES
# SELECT * 
FROM BOOK_SALES A
INNER JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(sales_date, "%y-%m") = "22-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY